1. Create a null vector of size 10 but the fifth value which is 1

In [1]:
import numpy as np

null_vector = np.zeros(10)

null_vector[4] = 1

print(null_vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


2.Create a vector with values ranging from 10 to 49

In [2]:
import numpy as np

vector = np.arange(10, 50)

print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


 3.Create a 3x3 matrix with values ranging from 0 to 8

In [3]:
import numpy as np
matrix = np.arange(9).reshape(3, 3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [4]:
import numpy as np
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)
print(non_zero_indices)


(array([0, 1, 4]),)


5.Create a 10x10 array with random values and find the minimum and maximum values

In [9]:
import numpy as np
random_array = np.random.rand(10, 10)
minimum_value = random_array.min()
maximum_value = random_array.max()
print(random_array)
print(f"Minimum Value: {minimum_value}")
print(f"Maximum Value: {maximum_value}")


[[0.38560257 0.09956    0.01056996 0.43281891 0.18761287 0.27911095
  0.19760897 0.94205819 0.29562627 0.18581867]
 [0.65068269 0.99487314 0.44763566 0.25488467 0.56431484 0.60128714
  0.96642675 0.43309916 0.84499576 0.54351994]
 [0.21205803 0.9465078  0.39897459 0.31915028 0.08943237 0.63136093
  0.12298426 0.41661697 0.10339161 0.83763448]
 [0.41764618 0.06408743 0.97374251 0.9094993  0.52571424 0.2617122
  0.11620618 0.95489671 0.75872542 0.73355741]
 [0.09623282 0.86954129 0.62259427 0.86625548 0.02772302 0.45496287
  0.04964763 0.19202214 0.91401287 0.18167027]
 [0.85725167 0.64793171 0.79163675 0.21902366 0.83748663 0.03944326
  0.67535195 0.68377436 0.88138166 0.08934084]
 [0.24241644 0.71193599 0.66572939 0.94195094 0.44167709 0.3981714
  0.88156599 0.83222479 0.05153258 0.74382211]
 [0.50708856 0.6522109  0.30146178 0.34949847 0.72143032 0.83727367
  0.33503013 0.81193267 0.62095819 0.10307506]
 [0.37320721 0.59543295 0.62517286 0.33746235 0.94171576 0.5212148
  0.69029716 0.

6.Create a random vector of size 30 and find the mean value.

In [11]:
import numpy as np
random_vector = np.random.rand(30)
mean_value = random_vector.mean()
print(random_vector)
print(f"Mean Value: {mean_value}")


[0.13733364 0.74649437 0.90824643 0.72215421 0.26419158 0.9630318
 0.44984949 0.07915363 0.33339886 0.19761914 0.89954667 0.87311768
 0.63817548 0.84658782 0.48126842 0.86462595 0.04445047 0.67958363
 0.35336144 0.46124391 0.10986272 0.94382525 0.61493964 0.89667191
 0.9371302  0.89300919 0.59009086 0.0643891  0.26686234 0.29006495]
Mean Value: 0.5516760263782163
